CREATE PROC FI_SP_VerificaCliente  
 @CPF VARCHAR(14)  
AS  
BEGIN  
 DECLARE @Count INT = 0;

 SET @Count += (SELECT SUM(1) FROM CLIENTES WHERE CPF = @CPF)
 SET @Count += (SELECT SUM(1) FROM BENEFICIARIOS WHERE CPF = @CPF)

SELECT @Count AS [COUNT]
END